# Generated by Django 2.1.7 on 2019-03-27 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LabelPost',
        ),
    ]
