# Generated by Django 2.1.7 on 2019-03-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_delete_labelpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
