# Generated by Django 2.1.7 on 2019-03-28 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_perpetratorentity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateentity',
            name='seed',
        ),
        migrations.RemoveField(
            model_name='injuredentity',
            name='seed',
        ),
        migrations.RemoveField(
            model_name='killedentity',
            name='seed',
        ),
        migrations.DeleteModel(
            name='LabelPost',
        ),
        migrations.RemoveField(
            model_name='locationentity',
            name='seed',
        ),
        migrations.RemoveField(
            model_name='perpetratorentity',
            name='seed',
        ),
        migrations.DeleteModel(
            name='DateEntity',
        ),
        migrations.DeleteModel(
            name='InjuredEntity',
        ),
        migrations.DeleteModel(
            name='KilledEntity',
        ),
        migrations.DeleteModel(
            name='LocationEntity',
        ),
        migrations.DeleteModel(
            name='PerpetratorEntity',
        ),
    ]
