# Generated by Django 2.1.7 on 2019-03-28 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190328_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateEntity',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('start_index', models.IntegerField()),
                ('end_index', models.IntegerField()),
                ('date_str', models.CharField(max_length=50)),
                ('date', models.DateTimeField(null=True)),
                ('seed',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='date_entity',
                     to='web.Article')),
            ],
            options={
                'db_table': 'date_entity',
            },
        ),
        migrations.CreateModel(
            name='InjuredEntity',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('start_index', models.IntegerField()),
                ('end_index', models.IntegerField()),
                ('num_injured', models.IntegerField()),
                ('seed',
                 models.OneToOneField(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='injured_entity',
                     to='web.Article')),
            ],
            options={
                'db_table': 'injured_entity',
            },
        ),
        migrations.CreateModel(
            name='KilledEntity',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('start_index', models.IntegerField()),
                ('end_index', models.IntegerField()),
                ('num_killed', models.IntegerField()),
                ('seed',
                 models.OneToOneField(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='killed_entity',
                     to='web.Article')),
            ],
            options={
                'db_table': 'killed_entity',
            },
        ),
        migrations.CreateModel(
            name='LabelPost',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('urls', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'labelpost',
            },
        ),
        migrations.CreateModel(
            name='LocationEntity',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('start_index', models.IntegerField()),
                ('end_index', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('seed',
                 models.OneToOneField(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='location_entity',
                     to='web.Article')),
            ],
            options={
                'db_table': 'location_entity',
            },
        ),
        migrations.CreateModel(
            name='PerpetratorEntity',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('start_index', models.IntegerField()),
                ('end_index', models.IntegerField()),
                ('perpetrator', models.CharField(max_length=100)),
                ('seed',
                 models.OneToOneField(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='perpetrator_entity',
                     to='web.Article')),
            ],
            options={
                'db_table': 'perpetrator_entity',
            },
        ),
    ]
