# Generated by Django 2.1.7 on 2019-03-31 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_article_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='type',
            new_name='article_type',
        ),
    ]
