# Generated by Django 2.1.7 on 2019-04-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_article_article_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationentity',
            name='location',
        ),
        migrations.AddField(
            model_name='locationentity',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
