# Generated by Django 2.1.7 on 2019-04-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20190402_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationentity',
            name='region',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
