# Generated by Django 2.1.7 on 2019-04-03 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20190402_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injuredentity',
            name='seed',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='injured_entities',
                to='web.Article'),
        ),
        migrations.AlterField(
            model_name='killedentity',
            name='seed',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='killed_entities',
                to='web.Article'),
        ),
    ]
