# Generated by Django 2.1.7 on 2019-04-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20190403_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='injuredentity',
            old_name='num_injured',
            new_name='num',
        ),
        migrations.RenameField(
            model_name='killedentity',
            old_name='num_killed',
            new_name='num',
        ),
        migrations.RemoveField(
            model_name='injuredentity',
            name='end_index',
        ),
        migrations.RemoveField(
            model_name='injuredentity',
            name='start_index',
        ),
        migrations.RemoveField(
            model_name='killedentity',
            name='end_index',
        ),
        migrations.RemoveField(
            model_name='killedentity',
            name='start_index',
        ),
        migrations.AddField(
            model_name='injuredentity',
            name='victim_end_index',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='injuredentity',
            name='victim_start_index',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='killedentity',
            name='victim_end_index',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='killedentity',
            name='victim_start_index',
            field=models.IntegerField(null=True),
        ),
    ]
