# Generated by Django 2.1.7 on 2019-04-04 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20190403_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasualtyEntity',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('num', models.CharField(max_length=200, null=True)),
                ('start_index', models.IntegerField(null=True)),
                ('end_index', models.IntegerField(null=True)),
                ('casualty_type',
                 models.CharField(
                     choices=[('INJURY', 'INJURY'), ('DEATH', 'DEATH')],
                     max_length=100)),
                ('seed',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='casualties',
                     to='web.Article')),
            ],
            options={
                'db_table': 'casualty_entity',
            },
        ),
        migrations.CreateModel(
            name='VictimEntity',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('victim', models.CharField(max_length=200, null=True)),
                ('victim_start_index', models.IntegerField(null=True)),
                ('victim_end_index', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='injuredentity',
            name='seed',
        ),
        migrations.RemoveField(
            model_name='killedentity',
            name='seed',
        ),
        migrations.DeleteModel(name='InjuredEntity',),
        migrations.DeleteModel(name='KilledEntity',),
        migrations.AddField(
            model_name='casualtyentity',
            name='victim_entity',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='casualty',
                to='web.VictimEntity'),
        ),
    ]
