# Generated by Django 2.1.7 on 2019-04-04 07:56

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('web', '0015_auto_20190404_0755'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='victimentity',
            table='victim_entity',
        ),
    ]
