# Generated by Django 2.1.7 on 2019-04-10 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20190404_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casualtyentity',
            name='victim_entity',
        ),
        migrations.RemoveField(
            model_name='victimentity',
            name='victim_end_index',
        ),
        migrations.RemoveField(
            model_name='victimentity',
            name='victim_start_index',
        ),
        migrations.AddField(
            model_name='victimentity',
            name='end_index',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='victimentity',
            name='seed',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='victim', to='web.CasualtyEntity'),
        ),
        migrations.AddField(
            model_name='victimentity',
            name='start_index',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='casualtyentity',
            name='end_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='casualtyentity',
            name='num',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='casualtyentity',
            name='start_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='victimentity',
            name='victim',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
